// Server-side document generation for the £497 Full Governance Program.
//
// Each function below is the exact template-string logic ported out of the
// matching free tool's client-side useMemo block (DPIAGenerator.tsx,
// FRIAAssistant.tsx, AIUsePolicyGenerator.tsx, IncidentReportingChecklist.tsx,
// MonitoringPlanGenerator.tsx, DocumentationAssistant.tsx), unchanged in
// wording and citations, just moved to run from the shared intake mapper
// output on the server instead of component state in the browser.

import {
  PROGRAM_DATA_TYPES,
  PROGRAM_SAFEGUARDS,
  toDpiaInput,
  toFriaInput,
  toAiUsePolicyInput,
  toIncidentChecklistInput,
  toMonitoringPlanInput,
  toDocumentationInput,
} from "./program-intake";

function today(): string {
  return new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
}

// ── 1. DPIA screening ────────────────────────────────────────────────────

export function generateDpia(input: ReturnType<typeof toDpiaInput>): string {
  const { systemName, purpose, dataTypes, automatedDecision, systematicMonitoring, largeScale, safeguards } = input;

  const name = systemName.trim() || "[System / process name]";
  const purposeText = purpose.trim() || "[Describe what the AI system does and why]";

  const dataTypeLines = dataTypes.size
    ? [...dataTypes].map((v) => `- ${PROGRAM_DATA_TYPES.find((d) => d.value === v)?.label}`).join("\n")
    : "- [No data types selected yet]";

  const safeguardLines = safeguards.size
    ? [...safeguards].map((v) => `- ${PROGRAM_SAFEGUARDS.find((s) => s.value === v)?.label}`).join("\n")
    : "- None recorded yet — this is the section most likely to draw a regulator's attention";

  const hasSpecialCategory = dataTypes.has("special_category") || dataTypes.has("children") || dataTypes.has("criminal");
  const dpiaRequired = hasSpecialCategory || automatedDecision || systematicMonitoring || (largeScale && dataTypes.size > 0 && !dataTypes.has("none"));

  const riskFactors: string[] = [];
  if (hasSpecialCategory) riskFactors.push("Processes special category, children's, or criminal offence data — Article 9/10 UK GDPR applies");
  if (automatedDecision) riskFactors.push("Involves automated decision-making with legal or similarly significant effect on individuals — Article 22 UK GDPR applies");
  if (systematicMonitoring) riskFactors.push("Involves systematic monitoring of individuals");
  if (largeScale) riskFactors.push("Processing is large scale");
  if (!riskFactors.length) riskFactors.push("No high-risk factors selected — screening below is based on current answers only");

  return `DATA PROTECTION IMPACT ASSESSMENT — SCREENING
Generated by Red Flag AI Pro, ${today()}

1. SYSTEM / PROCESS
${name}

2. DESCRIPTION OF PROCESSING
${purposeText}

3. DATA TYPES PROCESSED
${dataTypeLines}

4. RISK FACTORS IDENTIFIED
${riskFactors.map((r) => `- ${r}`).join("\n")}

5. NECESSITY & PROPORTIONALITY
Is there a less intrusive way to achieve the same purpose? [Answer before finalizing — this question has to be answered, not skipped, for the assessment to be genuine rather than a formality.]

6. SAFEGUARDS IN PLACE
${safeguardLines}

7. SCREENING OUTCOME
${dpiaRequired
  ? "A full DPIA is required under UK GDPR Article 35(3) before this processing begins or continues. At least one high-risk factor above triggers the requirement — this is not optional."
  : "Based on the factors selected, a full DPIA is not automatically required under Article 35(3). Completing one anyway is still good practice, and this screening should be revisited if the processing changes."}

8. SIGN-OFF
Assessed by: ______________________     Date: ______________
Reviewed by (DPO or equivalent): ______________________     Date: ______________

This is a screening document, not legal advice. It follows the ICO's own DPIA screening checklist structure. If the outcome above says a full DPIA is required, complete one before processing begins — the ICO's full DPIA template is linked below.`;
}

// ── 2. FRIA draft ────────────────────────────────────────────────────────

export function generateFria(input: ReturnType<typeof toFriaInput>): string {
  const { systemName, processes, usagePeriod, affectedParties, specificRisks, oversightMeasures, mitigationMeasures } = input;
  const name = systemName.trim() || "[AI system name]";

  return `FUNDAMENTAL RIGHTS IMPACT ASSESSMENT — DRAFT (Article 27)
Generated by Red Flag AI Pro, ${today()}

This is a preparation draft, not a submitted assessment. If your organization is required to file this (see the note below), results go to the market surveillance authority on the AI Office's own template.

SYSTEM: ${name}

1. DEPLOYER PROCESSES
${processes.trim() || "[Describe the processes in which this high-risk AI system will actually be used]"}

2. PERIOD AND FREQUENCY OF USE
${usagePeriod.trim() || "[How long, and how often, is this system intended to be used?]"}

3. AFFECTED PERSONS AND GROUPS
${affectedParties.trim() || "[Which categories of natural persons or groups are likely to be affected by its use?]"}

4. SPECIFIC RISKS OF HARM
${specificRisks.trim() || "[For each affected category above, what specific risks of harm to their fundamental rights does this pose?]"}

5. HUMAN OVERSIGHT MEASURES
${oversightMeasures.trim() || "[How will human oversight be implemented, per the system's instructions for use?]"}
See boundary authorization records for a way to make this provable, not just described: redflagaipro.com/boundary-authorization-records

6. RISK MITIGATION MEASURES
${mitigationMeasures.trim() || "[What measures will be taken if these risks materialize? Include internal governance arrangements and complaint mechanisms.]"}

WHO NEEDS TO FILE THIS
Article 27 applies to: public bodies governed by public law, private entities providing public services, and deployers of high-risk systems in specific Annex III categories (biometric verification/emotion recognition context, and credit scoring/insurance risk assessment). It must be done before first deployment and updated if any element changes.

This draft covers the 6 elements listed in Article 27(1). The Commission's actual submission template may itemize this differently — confirm on the live AI Office portal, and confirm with counsel whether your organization is in scope at all.`;
}

// ── 3. AI use policy ─────────────────────────────────────────────────────

const APPROVED_TOOLS = [
  { value: "listed", label: "Only tools on an approved list" },
  { value: "category", label: "Any tool in approved categories (e.g. writing, coding, research)" },
  { value: "open", label: "Open, with a duty to disclose what's used" },
  // The program mapper collapses architecture into either "in_house" or
  // "approved_tools" (see toAiUsePolicyInput) — "approved_tools" reuses the
  // "listed" wording as the sensible default for a company buying a done for
  // you policy rather than authoring its own tool list from scratch.
  { value: "in_house", label: "Only tools on an approved list" },
  { value: "approved_tools", label: "Only tools on an approved list" },
];

export function generateAiUsePolicy(input: ReturnType<typeof toAiUsePolicyInput>): string {
  const { companyName, approvedApproach, prohibitedUses, dataRules, approvalProcess, reportingChannel } = input;
  const name = companyName.trim() || "[Company name]";
  const approach = APPROVED_TOOLS.find((a) => a.value === approvedApproach)?.label ?? APPROVED_TOOLS[0].label;

  return `AI ACCEPTABLE USE POLICY — DRAFT
${name}
Generated by Red Flag AI Pro, ${today()}

This policy exists to give staff a clear answer to "can I use this AI tool for this," and to satisfy the EU AI Act Article 4 requirement to take measures ensuring sufficient AI literacy among staff using AI systems on the company's behalf.

1. WHO THIS APPLIES TO
All employees, contractors, and anyone using an AI tool in the course of work for ${name}.

2. APPROVED TOOL APPROACH
${approach}

3. PROHIBITED USES
${prohibitedUses.trim() || "[e.g. entering client confidential data into a public AI tool, using AI output as final legal or medical advice without review, making employment or disciplinary decisions based solely on AI output]"}

4. DATA HANDLING RULES
${dataRules.trim() || "[What data can and can't be entered into an AI tool — customer PII, unreleased financials, source code, etc.]"}

5. APPROVAL PROCESS FOR NEW TOOLS
${approvalProcess.trim() || "[Who signs off on adopting a new AI tool, and what they check before approving it]"}
See boundary authorization records for making this approval provable, not just a policy line: redflagaipro.com/boundary-authorization-records

6. REPORTING AND ESCALATION
${reportingChannel.trim() || "[Who staff tell if an AI tool produces something wrong, harmful, or if they're unsure whether a use is allowed]"}

7. REVIEW
This policy should be reviewed whenever new AI tools are adopted, and at minimum annually.

Version: ______________     Date: ______________     Owner: ______________________

This is a policy draft, not legal advice. It's a starting point to adapt to your actual tools and risk profile, not a finished, board-ready document.`;
}

// ── 4. Incident reporting checklist ─────────────────────────────────────

type IncidentType = "data_breach" | "harmful_decision" | "safety_malfunction" | "security_breach";
type Jurisdiction = "uk" | "eu" | "us";

const INCIDENT_TYPES: { value: IncidentType; label: string }[] = [
  { value: "data_breach", label: "Personal data breach" },
  { value: "harmful_decision", label: "AI made a harmful or discriminatory decision" },
  { value: "safety_malfunction", label: "Safety or serious malfunction" },
  { value: "security_breach", label: "Security breach of the AI system itself" },
];

const JURISDICTIONS: { value: Jurisdiction; label: string }[] = [
  { value: "uk", label: "United Kingdom" },
  { value: "eu", label: "European Union" },
  { value: "us", label: "United States" },
];

interface Guidance {
  deadline: string;
  notify: string[];
  authority: string;
  citation: string;
}

const GUIDANCE: Record<Jurisdiction, Record<IncidentType, Guidance>> = {
  uk: {
    data_breach: {
      deadline: "Within 72 hours of becoming aware, if it's likely to risk people's rights and freedoms",
      notify: ["The ICO (Information Commissioner's Office)", "Affected individuals, without undue delay, if the risk is high"],
      authority: "ico.org.uk/for-organisations/report-a-breach",
      citation: "UK GDPR Article 33 (regulator) and Article 34 (individuals)",
    },
    harmful_decision: {
      deadline: "As soon as practicable — most sector regulators expect prompt disclosure, not a fixed statutory clock for this category alone",
      notify: ["Anyone directly harmed by the decision", "Your DPO or governance lead, immediately, to open an investigation", "The relevant sector regulator if the decision falls under their remit (FCA, EHRC, etc.)"],
      authority: "Depends on sector — start with your own governance/legal lead",
      citation: "UK GDPR Article 22 (automated decisions) and Equality Act 2010 where discrimination is involved",
    },
    safety_malfunction: {
      deadline: "Immediately internally; external reporting timeline depends on the sector regulator involved",
      notify: ["Internal safety/governance lead immediately", "Sector regulator if safety-critical (HSE, MHRA, CAA, etc. depending on domain)"],
      authority: "Sector-specific — identify your regulator before an incident happens, not during one",
      citation: "General product/consumer safety duties, plus any sector-specific safety regime that applies",
    },
    security_breach: {
      deadline: "Within 72 hours if any personal data was exposed as a result",
      notify: ["The ICO if personal data was involved", "NCSC for significant cyber incidents (voluntary but recommended)"],
      authority: "ico.org.uk/for-organisations/report-a-breach",
      citation: "UK GDPR Article 33 where personal data is affected",
    },
  },
  eu: {
    data_breach: {
      deadline: "Within 72 hours of becoming aware, if it's likely to risk people's rights and freedoms",
      notify: ["Your lead supervisory authority", "Affected individuals, without undue delay, if the risk is high"],
      authority: "Your national data protection authority",
      citation: "GDPR Article 33 (regulator) and Article 34 (individuals)",
    },
    harmful_decision: {
      deadline: "If it qualifies as a serious incident from a high-risk AI system: without undue delay, and no later than 15 days after becoming aware. Shorter windows apply for death or serious disruption to critical infrastructure.",
      notify: ["The market surveillance authority in the relevant member state", "Affected individuals where applicable"],
      authority: "Your national market surveillance authority for the EU AI Act",
      citation: "EU AI Act Article 73 (serious incident reporting) — confirm exact deadline for your specific case with counsel, the shortened windows are fact-specific",
    },
    safety_malfunction: {
      deadline: "Without undue delay, no later than 15 days after becoming aware for most serious incidents; as little as 2 days if there's widespread infringement or serious disruption to critical infrastructure",
      notify: ["The market surveillance authority in the relevant member state", "Affected users or the public if there's ongoing risk"],
      authority: "Your national market surveillance authority",
      citation: "EU AI Act Article 73",
    },
    security_breach: {
      deadline: "Within 72 hours if personal data was exposed; separately assess against Article 73 if the AI system itself is high-risk",
      notify: ["Your lead supervisory authority if personal data was involved", "Market surveillance authority if the compromised system is high-risk under the AI Act"],
      authority: "Your national data protection authority and/or market surveillance authority",
      citation: "GDPR Article 33 and, where applicable, EU AI Act Article 73",
    },
  },
  us: {
    data_breach: {
      deadline: "No single federal deadline — governed state by state, most require notification within 30 to 60 days, some sectors (health, finance) have their own federal rules",
      notify: ["Your state Attorney General, per your state's specific breach law", "Affected individuals, per your state's specific breach law", "HHS if HIPAA-covered health data (60 days), or your sector regulator if GLBA/other sector law applies"],
      authority: "Varies by state — check the specific state's breach notification statute",
      citation: "State breach notification laws (all 50 states have one, requirements differ), plus HIPAA/GLBA where applicable",
    },
    harmful_decision: {
      deadline: "No single federal statutory clock — the FTC treats unfair or deceptive AI-driven decisions as an enforcement matter, act as fast as you would for any consumer harm",
      notify: ["Anyone directly harmed by the decision", "Your legal/compliance lead immediately", "The FTC or relevant sector regulator if it affects consumers at scale"],
      authority: "FTC (ftc.gov) for consumer-facing harms, or your sector regulator",
      citation: "FTC Act Section 5 (unfair or deceptive practices), sector-specific rules (ECOA for credit, etc.) where they apply",
    },
    safety_malfunction: {
      deadline: "Depends entirely on sector — no single federal AI safety incident clock exists yet",
      notify: ["Internal safety/legal lead immediately", "Sector regulator (FDA, NHTSA, CPSC, etc.) if it falls under an existing safety regime"],
      authority: "Sector-specific — identify your regulator before an incident happens",
      citation: "General product liability duties, plus any sector-specific safety regime that applies",
    },
    security_breach: {
      deadline: "Governed by the same state breach laws as a data breach if personal data was exposed",
      notify: ["Your state Attorney General and affected individuals per state law, if personal data was involved", "CISA for significant cyber incidents (voluntary but recommended for critical infrastructure)"],
      authority: "Varies by state",
      citation: "State breach notification laws where personal data is involved",
    },
  },
};

export function generateIncidentChecklist(input: ReturnType<typeof toIncidentChecklistInput>): string {
  const { incidentType, jurisdiction } = input;
  const guidance = GUIDANCE[jurisdiction][incidentType];
  const incidentLabel = INCIDENT_TYPES.find((t) => t.value === incidentType)?.label ?? "";
  const jurisdictionLabel = JURISDICTIONS.find((j) => j.value === jurisdiction)?.label ?? "";

  return `INCIDENT REPORTING CHECKLIST
Generated by Red Flag AI Pro, ${today()}

INCIDENT TYPE: ${incidentLabel}
JURISDICTION: ${jurisdictionLabel}

DEADLINE
${guidance.deadline}

WHO TO NOTIFY
${guidance.notify.map((n) => `- ${n}`).join("\n")}

REPORT TO
${guidance.authority}

LEGAL BASIS
${guidance.citation}

BEFORE YOU REPORT, RECORD:
- What happened and when you first became aware of it (the clock starts from awareness, not from when the incident occurred)
- Who is affected, and how many people
- What data or decision was involved
- What you've already done to contain it
- Who inside your organization is accountable for the response

This is guidance, not legal advice, and deadlines above are general figures that can shift based on the specific facts of an incident. Confirm the exact deadline and notification requirements with legal counsel before your clock runs out.`;
}

// ── 5. Post-market monitoring plan ──────────────────────────────────────

export function generateMonitoringPlan(input: ReturnType<typeof toMonitoringPlanInput>): string {
  const { systemName, metrics, dataSources, reviewCadence, thresholds, corrective, recordKeeping } = input;
  const name = systemName.trim() || "[AI system name]";

  return `POST-MARKET MONITORING PLAN — DRAFT (Article 72)
Generated by Red Flag AI Pro, ${today()}

This is a plan, not the monitoring itself. It documents how you intend to watch this system's performance over time. Actually collecting and analyzing the data described below requires your own infrastructure — this tool doesn't ingest or monitor anything live.

SYSTEM: ${name}

1. PERFORMANCE METRICS AND BASELINES
${metrics.trim() || "[What metrics will you track — accuracy, error rate, complaint volume, override rate — and what's the baseline value for each?]"}

2. DATA SOURCES AND COLLECTION METHOD
${dataSources.trim() || "[Where does this data come from, and how is it collected — logs, user reports, sampled review?]"}

3. REVIEW CADENCE
${reviewCadence.trim() || "[How often is this data analyzed, and by whom?]"}

4. ESCALATION THRESHOLDS
${thresholds.trim() || "[What values or changes trigger escalation — a metric crossing a line, a spike in complaints?]"}

5. CORRECTIVE ACTION PROCEDURE
${corrective.trim() || "[What happens when a threshold is crossed — who is notified, what's the response process?]"}

6. RECORD-KEEPING FORMAT
${recordKeeping.trim() || "[How is monitoring data and each review kept, in a form a regulator could later verify?]"}

This plan becomes part of your Annex IV technical documentation. The Commission's own implementing act sets the formal template and full list of required elements (due by 2 February 2026) — confirm the current official template before finalizing, as this draft may not match its exact structure.`;
}

// ── 6. Annex IV technical documentation ─────────────────────────────────

const ARCHITECTURE_TYPES: Record<string, string> = {
  rule_based: "Rule-based / decision logic (no machine learning)",
  classic_ml: "Classic machine learning (regression, classifier, etc.)",
  llm: "Large language model, used directly or fine-tuned",
  hybrid: "Hybrid — a mix of the above",
  // The program mapper passes through the intake's own architecture values
  // (third_party_api / fine_tuned / in_house / hybrid), which don't share
  // the free tool's vocabulary one for one — mapped to the closest label.
  third_party_api: "Large language model, used directly or fine-tuned",
  fine_tuned: "Large language model, used directly or fine-tuned",
  in_house: "Classic machine learning (regression, classifier, etc.)",
};

export function generateDocumentation(input: ReturnType<typeof toDocumentationInput>): string {
  const { systemName, purpose, architecture, dataSources, riskMeasures, oversight, testing, limitations } = input;
  const name = systemName.trim() || "[System name]";
  const archLabel = ARCHITECTURE_TYPES[architecture] ?? ARCHITECTURE_TYPES.hybrid;

  return `AI SYSTEM TECHNICAL DOCUMENTATION — DRAFT
Generated by Red Flag AI Pro, ${today()}

This is a documentation draft, not a certified conformity assessment. It organizes what you already know into the structure EU AI Act Annex IV expects. It does not independently verify any answer below.

1. SYSTEM NAME
${name}

2. INTENDED PURPOSE
${purpose.trim() || "[Describe what the system is for, who uses it, and what decision or output it produces]"}

3. DESIGN AND ARCHITECTURE
Type: ${archLabel}
${dataSources.trim() ? `Data sources: ${dataSources.trim()}` : "Data sources: [Describe what data trains or informs the system, and where it comes from]"}

4. RISK MANAGEMENT MEASURES
${riskMeasures.trim() || "[Describe what's been done to identify and reduce risks from this system — testing, guardrails, limits on autonomy]"}

5. HUMAN OVERSIGHT
${oversight.trim() || "[Describe how a human can intervene before a decision takes effect, not just review it after]"}
See boundary authorization records for a way to make this provable, not just described: redflagaipro.com/boundary-authorization-records

6. TESTING AND VALIDATION
${testing.trim() || "[Describe how the system was tested before deployment, and what the results showed]"}

7. KNOWN LIMITATIONS AND FORESEEABLE MISUSE
${limitations.trim() || "[Describe what the system is not designed to do, and how it could be misused]"}

8. VERSION AND CHANGE LOG
Version: ______________     Date: ______________
Next review due: ______________

9. PREPARED BY
Name: ______________________     Role: ______________________     Date: ______________

This draft follows the structure of EU AI Act Annex IV. It is not a substitute for a full conformity assessment, legal advice, or certification by an accredited body. Confirm what applies to your specific system with legal counsel.`;
}

// ── Bundle: run all six from one shared intake ──────────────────────────

export interface ProgramDocumentBundle {
  dpia: string;
  fria: string;
  ai_use_policy: string;
  incident_checklist: string;
  monitoring_plan: string;
  documentation: string;
}

// Single source of truth for each document's human label and display order,
// used by the enhancement layer, the seal record, and the delivery page so
// none of them can drift out of step with each other.
export const DOCUMENT_LABELS: { key: keyof ProgramDocumentBundle; label: string }[] = [
  { key: "dpia", label: "Data Protection Impact Assessment screening" },
  { key: "fria", label: "Fundamental Rights Impact Assessment draft" },
  { key: "ai_use_policy", label: "AI Acceptable Use Policy draft" },
  { key: "incident_checklist", label: "Incident reporting checklist" },
  { key: "monitoring_plan", label: "Post market monitoring plan draft" },
  { key: "documentation", label: "Annex IV technical documentation draft" },
];

export function generateAllProgramDocuments(intake: {
  companyName: string;
  systemName: string;
  purpose: string;
  architecture: string;
  primaryJurisdiction: string;
  dataTypes: string[];
  dataSources: string;
  automatedDecision: boolean;
  systematicMonitoring: boolean;
  largeScale: boolean;
  safeguards: string[];
  oversightMeasures: string;
  mitigationMeasures: string;
  testing: string;
  limitations: string;
  affectedParties: string;
  usagePeriod: string;
  specificRisks: string;
  metrics: string;
  reviewCadence: string;
  thresholds: string;
  correctiveAction: string;
  recordKeeping: string;
  prohibitedUses: string;
  dataRules: string;
  approvalProcess: string;
  reportingChannel: string;
}): ProgramDocumentBundle {
  // Cast is safe: the intake read back from Supabase jsonb has the same
  // shape as ProgramIntake, just without the branded union types enforced —
  // the mapper functions only ever read known string/boolean/array fields.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const i = intake as any;

  return {
    dpia: generateDpia(toDpiaInput(i)),
    fria: generateFria(toFriaInput(i)),
    ai_use_policy: generateAiUsePolicy(toAiUsePolicyInput(i)),
    incident_checklist: generateIncidentChecklist(toIncidentChecklistInput(i)),
    monitoring_plan: generateMonitoringPlan(toMonitoringPlanInput(i)),
    documentation: generateDocumentation(toDocumentationInput(i)),
  };
}
