import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { ScanResultCard } from "@/components/scans/ScanResultCard";
import { FlagList } from "@/components/scans/FlagList";
import type { Plan, Scan, ScanFlag } from "@/types";

export default async function PrintScanPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) notFound();

  const [{ data: scan }, { data: flags }, { data: profile }] =
    await Promise.all([
      supabase
        .from("scans")
        .select("*")
        .eq("id", id)
        .eq("user_id", user.id)
        .single(),
      supabase.from("scan_flags").select("*").eq("scan_id", id),
      supabase
        .from("profiles")
        .select("plan")
        .eq("user_id", user.id)
        .single(),
    ]);

  if (!scan) notFound();

  const plan: Plan = (profile?.plan as Plan) ?? "free";
  if (plan === "free") notFound();

  const dateStr = new Date(scan.created_at).toLocaleDateString("en-GB", {
    year: "numeric", month: "long", day: "numeric",
  });

  return (
    <div className="min-h-screen bg-[#0A1628] px-10 py-10">
      <div className="mx-auto max-w-3xl space-y-6">
        <div className="flex items-center justify-between border-b border-white/10 pb-4">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/redflag-logo-full.png" alt="Red Flag AI Pro" width={140} height={110} className="object-contain" />
          <div className="text-right">
            <p className="text-sm font-bold text-[#E5484D]">Compliance Risk Report</p>
            <p className="text-xs text-[rgba(244,241,234,0.4)]">Generated {dateStr} · redflagaipro.com</p>
          </div>
        </div>

        <ScanResultCard
          scan={scan as Scan}
          flags={(flags ?? []) as ScanFlag[]}
          plan={plan}
          print
        />

        <div>
          <h2 className="mb-3 text-lg font-bold text-[#F4F1EA]">
            Compliance Flags
          </h2>
          <FlagList flags={(flags ?? []) as ScanFlag[]} score={scan.score} />
        </div>

        <p className="pt-4 text-center text-[10px] text-[rgba(244,241,234,0.25)]">
          Generated by Red Flag AI Pro · redflagaipro.com · Confidential
        </p>
      </div>
    </div>
  );
}
