"use client";

import { useMemo, useState } from "react";
import React from "react";
import { ResultsGate } from "./ResultsGate";

const syne = { fontFamily: "'Syne', system-ui, sans-serif" } as React.CSSProperties;
const mono = { fontFamily: "'DM Mono', 'Courier New', monospace" } as React.CSSProperties;

export function AILiteracyLog() {
  const [companyName, setCompanyName] = useState("");
  const [audiences, setAudiences] = useState("");
  const [trainingGiven, setTrainingGiven] = useState("");
  const [tailoring, setTailoring] = useState("");
  const [frequency, setFrequency] = useState("");
  const [evidenceKept, setEvidenceKept] = useState("");
  const [copied, setCopied] = useState(false);

  const output = useMemo(() => {
    const name = companyName.trim() || "[Company name]";
    return `AI LITERACY MEASURES LOG (Article 4)
${name}
Generated by Red Flag AI Pro, ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}

Article 4 requires taking measures to ensure sufficient AI literacy among staff and others using AI systems on the company's behalf, including contractors and service providers. There's no fixed checklist in the text — the obligation is to show you took proportionate, genuine measures, tailored to role and context.

1. WHO THIS COVERS
${audiences.trim() || "[Staff, contractors, service providers who use AI tools on the company's behalf — list roles/teams]"}

2. TRAINING OR MEASURES GIVEN
${trainingGiven.trim() || "[What was actually done — a training session, a written guide, onboarding material, a policy walkthrough]"}

3. HOW IT WAS TAILORED
${tailoring.trim() || "[How the measures accounted for each group's technical knowledge, experience, and the specific AI systems and context they work in — a blanket approach is weaker evidence than a tailored one]"}

4. FREQUENCY
${frequency.trim() || "[One-off at onboarding? Refreshed when new tools are adopted? Annual refresher?]"}

5. EVIDENCE KEPT
${evidenceKept.trim() || "[Attendance records, sign-off, quiz completion, or whatever shows the measure actually happened, not just that it was planned]"}

Log entry date: ______________     Recorded by: ______________________

This is a record-keeping template, not proof any specific measure satisfies Article 4 — proportionality is judged case by case. It exists so you have something to show if asked, rather than reconstructing it after the fact.`;
  }, [companyName, audiences, trainingGiven, tailoring, frequency, evidenceKept]);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard not available — text is selectable regardless
    }
  }

  const labelStyle: React.CSSProperties = {
    ...syne, fontSize: "10px", fontWeight: 700, letterSpacing: "0.18em", textTransform: "uppercase",
    color: "rgba(255,255,255,0.35)", marginBottom: "0.6rem", display: "block",
  };
  const inputStyle: React.CSSProperties = {
    width: "100%", background: "#0F2138", border: "1px solid rgba(255,255,255,0.18)", color: "rgba(255,255,255,0.9)",
    ...syne, fontSize: "14px", padding: "12px 14px", outline: "none", borderRadius: "6px",
  };
  const textareaStyle: React.CSSProperties = { ...inputStyle, resize: "vertical", fontFamily: "'Syne', system-ui, sans-serif" };

  return (
    <div>
      <div style={{
        background: "rgba(201,166,107,0.08)", border: "1px solid rgba(201,166,107,0.3)", borderLeft: "3px solid #C9A66B",
        padding: "1.25rem 1.5rem", marginBottom: "1.5rem",
      }}>
        <p style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.8)", lineHeight: 1.6 }}>
          Article 4 applies to every deployer of AI, not just high-risk systems — if anyone at the company uses an AI writing tool, chatbot, or analytics platform, this applies. It's been in force since February 2025.
        </p>
      </div>

      <div style={{ background: "#0F2138", border: "1px solid rgba(255,255,255,0.15)", padding: "2rem" }}>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Company name</label>
          <input type="text" value={companyName} onChange={(e) => setCompanyName(e.target.value)} style={inputStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Who this covers</label>
          <textarea value={audiences} onChange={(e) => setAudiences(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Training or measures given</label>
          <textarea value={trainingGiven} onChange={(e) => setTrainingGiven(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>How it was tailored to each group</label>
          <textarea value={tailoring} onChange={(e) => setTailoring(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Frequency</label>
          <textarea value={frequency} onChange={(e) => setFrequency(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div>
          <label style={labelStyle}>Evidence kept</label>
          <textarea value={evidenceKept} onChange={(e) => setEvidenceKept(e.target.value)} rows={2} style={textareaStyle} />
        </div>
      </div>

      <ResultsGate tool="ai-literacy-log" title="Enter your email to see your literacy log draft. Free, plus occasional updates, unsubscribe anytime.">
        <div style={{ marginTop: "1.5rem" }}>
          <div style={{ background: "#102943", border: "1px solid rgba(239,68,68,0.2)", borderLeft: "3px solid #E5484D", padding: "1.5rem 1.75rem" }}>
            <p style={labelStyle}>Your AI literacy log</p>
            <pre style={{ ...mono, fontSize: "12.5px", color: "rgba(255,255,255,0.85)", lineHeight: 1.7, marginBottom: "1.25rem", whiteSpace: "pre-wrap", wordBreak: "break-word" }}>
              {output}
            </pre>
            <button
              onClick={handleCopy}
              style={{
                background: copied ? "rgba(74,222,128,0.12)" : "#E5484D", color: copied ? "#4ade80" : "white",
                border: copied ? "1px solid rgba(74,222,128,0.3)" : "none", ...syne, fontSize: "0.85rem", fontWeight: 700,
                padding: "10px 22px", borderRadius: "9999px", cursor: "pointer", letterSpacing: "0.02em", transition: "all 0.2s",
              }}
            >
              {copied ? "Copied ✓" : "Copy to clipboard"}
            </button>
          </div>
        </div>
      </ResultsGate>

      <p style={{ ...syne, fontSize: "11px", color: "rgba(255,255,255,0.25)", lineHeight: 1.7, marginTop: "1.5rem", textAlign: "center" }}>
        This tool produces a record-keeping template, not legal advice or proof of compliance. Article 4 is a proportionality-based obligation with no fixed checklist — confirm what's adequate for your situation with legal counsel.
      </p>
    </div>
  );
}
