"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import React from "react";
import { ResultsGate } from "./ResultsGate";

const syne = { fontFamily: "'Syne', system-ui, sans-serif" } as React.CSSProperties;
const mono = { fontFamily: "'DM Mono', 'Courier New', monospace" } as React.CSSProperties;

const APPROVED_TOOLS = [
  { value: "listed", label: "Only tools on an approved list" },
  { value: "category", label: "Any tool in approved categories (e.g. writing, coding, research)" },
  { value: "open", label: "Open, with a duty to disclose what's used" },
];

export function AIUsePolicyGenerator() {
  const [companyName, setCompanyName] = useState("");
  const [approvedApproach, setApprovedApproach] = useState(APPROVED_TOOLS[0].value);
  const [prohibitedUses, setProhibitedUses] = useState("");
  const [dataRules, setDataRules] = useState("");
  const [approvalProcess, setApprovalProcess] = useState("");
  const [reportingChannel, setReportingChannel] = useState("");
  const [copied, setCopied] = useState(false);

  const output = useMemo(() => {
    const name = companyName.trim() || "[Company name]";
    const approach = APPROVED_TOOLS.find((a) => a.value === approvedApproach)?.label ?? "";

    return `AI ACCEPTABLE USE POLICY — DRAFT
${name}
Generated by Red Flag AI Pro, ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}

This policy exists to give staff a clear answer to "can I use this AI tool for this," and to satisfy the EU AI Act Article 4 requirement to take measures ensuring sufficient AI literacy among staff using AI systems on the company's behalf.

1. WHO THIS APPLIES TO
All employees, contractors, and anyone using an AI tool in the course of work for ${name}.

2. APPROVED TOOL APPROACH
${approach}

3. PROHIBITED USES
${prohibitedUses.trim() || "[e.g. entering client confidential data into a public AI tool, using AI output as final legal or medical advice without review, making employment or disciplinary decisions based solely on AI output]"}

4. DATA HANDLING RULES
${dataRules.trim() || "[What data can and can't be entered into an AI tool — customer PII, unreleased financials, source code, etc.]"}

5. APPROVAL PROCESS FOR NEW TOOLS
${approvalProcess.trim() || "[Who signs off on adopting a new AI tool, and what they check before approving it]"}
See boundary authorization records for making this approval provable, not just a policy line: redflagaipro.com/boundary-authorization-records

6. REPORTING AND ESCALATION
${reportingChannel.trim() || "[Who staff tell if an AI tool produces something wrong, harmful, or if they're unsure whether a use is allowed]"}

7. REVIEW
This policy should be reviewed whenever new AI tools are adopted, and at minimum annually.

Version: ______________     Date: ______________     Owner: ______________________

This is a policy draft, not legal advice. It's a starting point to adapt to your actual tools and risk profile, not a finished, board-ready document.`;
  }, [companyName, approvedApproach, prohibitedUses, dataRules, approvalProcess, reportingChannel]);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard not available — text is selectable regardless
    }
  }

  const labelStyle: React.CSSProperties = {
    ...syne, fontSize: "10px", fontWeight: 700, letterSpacing: "0.18em", textTransform: "uppercase",
    color: "rgba(255,255,255,0.35)", marginBottom: "0.6rem", display: "block",
  };
  const inputStyle: React.CSSProperties = {
    width: "100%", background: "#0F2138", border: "1px solid rgba(255,255,255,0.18)", color: "rgba(255,255,255,0.9)",
    ...syne, fontSize: "14px", padding: "12px 14px", outline: "none", borderRadius: "6px",
  };
  const textareaStyle: React.CSSProperties = { ...inputStyle, resize: "vertical", fontFamily: "'Syne', system-ui, sans-serif" };

  return (
    <div>
      <div style={{
        background: "rgba(201,166,107,0.08)", border: "1px solid rgba(201,166,107,0.3)", borderLeft: "3px solid #C9A66B",
        padding: "1.25rem 1.5rem", marginBottom: "1.5rem",
      }}>
        <p style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.8)", lineHeight: 1.6 }}>
          This is for your own staff using AI tools day to day — different from the affiliate/sponsorship disclosure generator, which is about disclosures you show your audience.
        </p>
      </div>

      <div style={{ background: "#0F2138", border: "1px solid rgba(255,255,255,0.15)", padding: "2rem" }}>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Company name</label>
          <input type="text" value={companyName} onChange={(e) => setCompanyName(e.target.value)} style={inputStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Which tools are staff allowed to use?</label>
          <select value={approvedApproach} onChange={(e) => setApprovedApproach(e.target.value)} style={{ ...inputStyle, appearance: "none" }}>
            {APPROVED_TOOLS.map((a) => (
              <option key={a.value} value={a.value} style={{ background: "#0F2138" }}>{a.label}</option>
            ))}
          </select>
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Prohibited uses</label>
          <textarea value={prohibitedUses} onChange={(e) => setProhibitedUses(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Data handling rules</label>
          <textarea value={dataRules} onChange={(e) => setDataRules(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Approval process for new tools</label>
          <textarea value={approvalProcess} onChange={(e) => setApprovalProcess(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div>
          <label style={labelStyle}>Reporting and escalation channel</label>
          <textarea value={reportingChannel} onChange={(e) => setReportingChannel(e.target.value)} rows={2} style={textareaStyle} />
        </div>
      </div>

      <ResultsGate tool="ai-use-policy-generator" title="Enter your email to see your policy draft. Free, plus occasional updates, unsubscribe anytime.">
        <div style={{ marginTop: "1.5rem" }}>
          <div style={{ background: "#102943", border: "1px solid rgba(239,68,68,0.2)", borderLeft: "3px solid #E5484D", padding: "1.5rem 1.75rem" }}>
            <p style={labelStyle}>Your AI use policy draft</p>
            <pre style={{ ...mono, fontSize: "12.5px", color: "rgba(255,255,255,0.85)", lineHeight: 1.7, marginBottom: "1.25rem", whiteSpace: "pre-wrap", wordBreak: "break-word" }}>
              {output}
            </pre>
            <button
              onClick={handleCopy}
              style={{
                background: copied ? "rgba(74,222,128,0.12)" : "#E5484D", color: copied ? "#4ade80" : "white",
                border: copied ? "1px solid rgba(74,222,128,0.3)" : "none", ...syne, fontSize: "0.85rem", fontWeight: 700,
                padding: "10px 22px", borderRadius: "9999px", cursor: "pointer", letterSpacing: "0.02em", transition: "all 0.2s",
              }}
            >
              {copied ? "Copied ✓" : "Copy to clipboard"}
            </button>
          </div>
        </div>
      </ResultsGate>

      <p style={{ ...syne, fontSize: "11px", color: "rgba(255,255,255,0.25)", lineHeight: 1.7, marginTop: "1.5rem", textAlign: "center" }}>
        This tool produces a policy draft, not legal advice. Adapt it to your actual tools, data and risk profile before adopting it, and have it reviewed by counsel if it will be relied on formally.
      </p>
    </div>
  );
}
