"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import React from "react";
import { ResultsGate } from "./ResultsGate";

const syne = { fontFamily: "'Syne', system-ui, sans-serif" } as React.CSSProperties;
const mono = { fontFamily: "'DM Mono', 'Courier New', monospace" } as React.CSSProperties;

const ARCHITECTURE_TYPES = [
  { value: "rule_based", label: "Rule-based / decision logic (no machine learning)" },
  { value: "classic_ml", label: "Classic machine learning (regression, classifier, etc.)" },
  { value: "llm", label: "Large language model, used directly or fine-tuned" },
  { value: "hybrid", label: "Hybrid — a mix of the above" },
];

export function DocumentationAssistant() {
  const [systemName, setSystemName] = useState("");
  const [purpose, setPurpose] = useState("");
  const [architecture, setArchitecture] = useState(ARCHITECTURE_TYPES[0].value);
  const [dataSources, setDataSources] = useState("");
  const [riskMeasures, setRiskMeasures] = useState("");
  const [oversight, setOversight] = useState("");
  const [testing, setTesting] = useState("");
  const [limitations, setLimitations] = useState("");
  const [copied, setCopied] = useState(false);

  const output = useMemo(() => {
    const name = systemName.trim() || "[System name]";
    const archLabel = ARCHITECTURE_TYPES.find((a) => a.value === architecture)?.label ?? "";

    return `AI SYSTEM TECHNICAL DOCUMENTATION — DRAFT
Generated by Red Flag AI Pro, ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}

This is a documentation draft, not a certified conformity assessment. It organizes what you already know into the structure EU AI Act Annex IV expects. It does not independently verify any answer below.

1. SYSTEM NAME
${name}

2. INTENDED PURPOSE
${purpose.trim() || "[Describe what the system is for, who uses it, and what decision or output it produces]"}

3. DESIGN AND ARCHITECTURE
Type: ${archLabel}
${dataSources.trim() ? `Data sources: ${dataSources.trim()}` : "Data sources: [Describe what data trains or informs the system, and where it comes from]"}

4. RISK MANAGEMENT MEASURES
${riskMeasures.trim() || "[Describe what's been done to identify and reduce risks from this system — testing, guardrails, limits on autonomy]"}

5. HUMAN OVERSIGHT
${oversight.trim() || "[Describe how a human can intervene before a decision takes effect, not just review it after]"}
See boundary authorization records for a way to make this provable, not just described: redflagaipro.com/boundary-authorization-records

6. TESTING AND VALIDATION
${testing.trim() || "[Describe how the system was tested before deployment, and what the results showed]"}

7. KNOWN LIMITATIONS AND FORESEEABLE MISUSE
${limitations.trim() || "[Describe what the system is not designed to do, and how it could be misused]"}

8. VERSION AND CHANGE LOG
Version: ______________     Date: ______________
Next review due: ______________

9. PREPARED BY
Name: ______________________     Role: ______________________     Date: ______________

This draft follows the structure of EU AI Act Annex IV. It is not a substitute for a full conformity assessment, legal advice, or certification by an accredited body. Confirm what applies to your specific system with legal counsel.`;
  }, [systemName, purpose, architecture, dataSources, riskMeasures, oversight, testing, limitations]);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard not available — text is selectable regardless
    }
  }

  const labelStyle: React.CSSProperties = {
    ...syne,
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.35)",
    marginBottom: "0.6rem",
    display: "block",
  };

  const inputStyle: React.CSSProperties = {
    width: "100%",
    background: "#0F2138",
    border: "1px solid rgba(255,255,255,0.18)",
    color: "rgba(255,255,255,0.9)",
    ...syne,
    fontSize: "14px",
    padding: "12px 14px",
    outline: "none",
    borderRadius: "6px",
  };

  const textareaStyle: React.CSSProperties = { ...inputStyle, resize: "vertical", fontFamily: "'Syne', system-ui, sans-serif" };

  return (
    <div>
      <div style={{
        background: "rgba(201,166,107,0.08)",
        border: "1px solid rgba(201,166,107,0.3)",
        borderLeft: "3px solid #C9A66B",
        padding: "1.25rem 1.5rem",
        marginBottom: "1.5rem",
      }}>
        <p style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.8)", lineHeight: 1.6 }}>
          This is a <strong>documentation assistant</strong>, not a conformity assessment. It organizes what you already know about your system into the structure regulators expect. It doesn&apos;t independently test, verify, or certify anything you enter.
        </p>
      </div>

      <div style={{
        background: "#0F2138",
        border: "1px solid rgba(255,255,255,0.15)",
        padding: "2rem",
        boxShadow: "0 0 0 1px rgba(255,255,255,0.04), inset 0 1px 0 rgba(255,255,255,0.04)"
      }}>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>System name</label>
          <input type="text" value={systemName} onChange={(e) => setSystemName(e.target.value)} placeholder="e.g. Loan application scoring model" style={inputStyle} />
        </div>

        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Intended purpose</label>
          <textarea value={purpose} onChange={(e) => setPurpose(e.target.value)} placeholder="What does it do, who uses it, what decision or output does it produce?" rows={2} style={textareaStyle} />
        </div>

        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Architecture type</label>
          <select value={architecture} onChange={(e) => setArchitecture(e.target.value)} style={{ ...inputStyle, appearance: "none" }}>
            {ARCHITECTURE_TYPES.map((a) => (
              <option key={a.value} value={a.value} style={{ background: "#0F2138" }}>{a.label}</option>
            ))}
          </select>
        </div>

        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Data sources</label>
          <textarea value={dataSources} onChange={(e) => setDataSources(e.target.value)} placeholder="What data trains or informs the system, and where does it come from?" rows={2} style={textareaStyle} />
        </div>

        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Risk management measures</label>
          <textarea value={riskMeasures} onChange={(e) => setRiskMeasures(e.target.value)} placeholder="What's been done to identify and reduce risk from this system?" rows={2} style={textareaStyle} />
        </div>

        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Human oversight</label>
          <textarea value={oversight} onChange={(e) => setOversight(e.target.value)} placeholder="How can a human intervene before a decision takes effect?" rows={2} style={textareaStyle} />
        </div>

        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Testing and validation</label>
          <textarea value={testing} onChange={(e) => setTesting(e.target.value)} placeholder="How was it tested before deployment, and what did testing show?" rows={2} style={textareaStyle} />
        </div>

        <div>
          <label style={labelStyle}>Known limitations and foreseeable misuse</label>
          <textarea value={limitations} onChange={(e) => setLimitations(e.target.value)} placeholder="What is it not designed to do? How could it be misused?" rows={2} style={textareaStyle} />
        </div>
      </div>

      <ResultsGate tool="documentation-assistant" title="Enter your email to see your documentation draft. Free, plus occasional updates, unsubscribe anytime.">
        <div style={{ marginTop: "1.5rem" }}>
          <div style={{
            background: "#102943",
            border: "1px solid rgba(239,68,68,0.2)",
            borderLeft: "3px solid #E5484D",
            padding: "1.5rem 1.75rem",
          }}>
            <p style={labelStyle}>Your documentation draft</p>
            <pre style={{ ...mono, fontSize: "12.5px", color: "rgba(255,255,255,0.85)", lineHeight: 1.7, marginBottom: "1.25rem", whiteSpace: "pre-wrap", wordBreak: "break-word" }}>
              {output}
            </pre>
            <button
              onClick={handleCopy}
              style={{
                background: copied ? "rgba(74,222,128,0.12)" : "#E5484D",
                color: copied ? "#4ade80" : "white",
                border: copied ? "1px solid rgba(74,222,128,0.3)" : "none",
                ...syne,
                fontSize: "0.85rem",
                fontWeight: 700,
                padding: "10px 22px",
                borderRadius: "9999px",
                cursor: "pointer",
                letterSpacing: "0.02em",
                transition: "all 0.2s",
              }}
            >
              {copied ? "Copied ✓" : "Copy to clipboard"}
            </button>
          </div>
        </div>
      </ResultsGate>

      <div style={{
        background: "#102943",
        border: "1px solid rgba(239,68,68,0.25)",
        padding: "2.25rem 2rem",
        textAlign: "center",
        marginTop: "1.5rem",
      }}>
        <p style={{ ...syne, fontSize: "1.1rem", fontWeight: 800, color: "white", letterSpacing: "-0.02em", marginBottom: "0.5rem" }}>
          This documents what you say your oversight is. It doesn&apos;t prove it happened.
        </p>
        <p style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.4)", lineHeight: 1.7, marginBottom: "1.5rem", maxWidth: "460px", margin: "0.5rem auto 1.5rem" }}>
          Boundary authorization records seal who approved a system, in what role, and under what condition, so the human oversight section above becomes a provable record instead of a paragraph.
        </p>
        <Link href="/boundary-authorization-records" style={{
          display: "inline-block",
          background: "#E5484D",
          color: "white",
          ...syne,
          fontSize: "0.9rem",
          fontWeight: 700,
          padding: "14px 32px",
          borderRadius: "9999px",
          boxShadow: "0 8px 32px rgba(229,72,77,0.18)",
          textDecoration: "none",
          letterSpacing: "0.02em",
        }}>
          See how boundary authorization works
        </Link>
      </div>

      <p style={{ ...syne, fontSize: "11px", color: "rgba(255,255,255,0.25)", lineHeight: 1.7, marginTop: "1.5rem", textAlign: "center" }}>
        This tool produces a documentation draft, not a conformity assessment, legal advice, or certification. It follows the structure of EU AI Act Annex IV but does not independently verify anything you enter. Confirm what applies to your system with legal counsel or an accredited conformity assessment body where one is required.
      </p>
    </div>
  );
}
