"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import React from "react";
import { ResultsGate } from "./ResultsGate";

const syne = { fontFamily: "'Syne', system-ui, sans-serif" } as React.CSSProperties;
const mono = { fontFamily: "'DM Mono', 'Courier New', monospace" } as React.CSSProperties;

const DATA_TYPES = [
  { value: "special_category", label: "Health, biometric, genetic, ethnicity, religion or similar special category data" },
  { value: "children", label: "Data belonging to children (under 18)" },
  { value: "financial", label: "Financial or credit information" },
  { value: "criminal", label: "Criminal offence or conviction data" },
  { value: "location", label: "Precise location or movement tracking" },
  { value: "standard_personal", label: "Standard personal data only (name, email, contact details)" },
  { value: "none", label: "No personal data — anonymized or aggregated only" },
] as const;

type DataType = (typeof DATA_TYPES)[number]["value"];

const SAFEGUARDS = [
  { value: "encryption", label: "Data encrypted at rest and in transit" },
  { value: "access_controls", label: "Role-based access controls in place" },
  { value: "human_review", label: "A human reviews outputs before they take effect" },
  { value: "retention_limits", label: "Defined retention period, data deleted after" },
  { value: "anonymization", label: "Data anonymized or pseudonymized where possible" },
  { value: "dpa", label: "Data processing agreement in place with any vendor" },
] as const;

type Safeguard = (typeof SAFEGUARDS)[number]["value"];

export function DPIAGenerator() {
  const [systemName, setSystemName] = useState("");
  const [purpose, setPurpose] = useState("");
  const [dataTypes, setDataTypes] = useState<Set<DataType>>(new Set());
  const [automatedDecision, setAutomatedDecision] = useState(false);
  const [systematicMonitoring, setSystematicMonitoring] = useState(false);
  const [largeScale, setLargeScale] = useState(false);
  const [safeguards, setSafeguards] = useState<Set<Safeguard>>(new Set());
  const [copied, setCopied] = useState(false);

  function toggleSet<T>(set: Set<T>, value: T, setter: (s: Set<T>) => void) {
    const next = new Set(set);
    if (next.has(value)) next.delete(value);
    else next.add(value);
    setter(next);
  }

  const hasSpecialCategory = dataTypes.has("special_category") || dataTypes.has("children") || dataTypes.has("criminal");
  const dpiaRequired = hasSpecialCategory || automatedDecision || systematicMonitoring || (largeScale && dataTypes.size > 0 && !dataTypes.has("none"));

  const output = useMemo(() => {
    const name = systemName.trim() || "[System / process name]";
    const purposeText = purpose.trim() || "[Describe what the AI system does and why]";

    const dataTypeLines = dataTypes.size
      ? [...dataTypes].map((v) => `- ${DATA_TYPES.find((d) => d.value === v)?.label}`).join("\n")
      : "- [No data types selected yet]";

    const safeguardLines = safeguards.size
      ? [...safeguards].map((v) => `- ${SAFEGUARDS.find((s) => s.value === v)?.label}`).join("\n")
      : "- None recorded yet — this is the section most likely to draw a regulator's attention";

    const riskFactors: string[] = [];
    if (hasSpecialCategory) riskFactors.push("Processes special category, children's, or criminal offence data — Article 9/10 UK GDPR applies");
    if (automatedDecision) riskFactors.push("Involves automated decision-making with legal or similarly significant effect on individuals — Article 22 UK GDPR applies");
    if (systematicMonitoring) riskFactors.push("Involves systematic monitoring of individuals");
    if (largeScale) riskFactors.push("Processing is large scale");
    if (!riskFactors.length) riskFactors.push("No high-risk factors selected — screening below is based on current answers only");

    return `DATA PROTECTION IMPACT ASSESSMENT — SCREENING
Generated by Red Flag AI Pro, ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}

1. SYSTEM / PROCESS
${name}

2. DESCRIPTION OF PROCESSING
${purposeText}

3. DATA TYPES PROCESSED
${dataTypeLines}

4. RISK FACTORS IDENTIFIED
${riskFactors.map((r) => `- ${r}`).join("\n")}

5. NECESSITY & PROPORTIONALITY
Is there a less intrusive way to achieve the same purpose? [Answer before finalizing — this question has to be answered, not skipped, for the assessment to be genuine rather than a formality.]

6. SAFEGUARDS IN PLACE
${safeguardLines}

7. SCREENING OUTCOME
${dpiaRequired
  ? "A full DPIA is required under UK GDPR Article 35(3) before this processing begins or continues. At least one high-risk factor above triggers the requirement — this is not optional."
  : "Based on the factors selected, a full DPIA is not automatically required under Article 35(3). Completing one anyway is still good practice, and this screening should be revisited if the processing changes."}

8. SIGN-OFF
Assessed by: ______________________     Date: ______________
Reviewed by (DPO or equivalent): ______________________     Date: ______________

This is a screening document, not legal advice. It follows the ICO's own DPIA screening checklist structure. If the outcome above says a full DPIA is required, complete one before processing begins — the ICO's full DPIA template is linked below.`;
  }, [systemName, purpose, dataTypes, safeguards, hasSpecialCategory, automatedDecision, systematicMonitoring, largeScale, dpiaRequired]);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard not available — text is selectable regardless
    }
  }

  const labelStyle: React.CSSProperties = {
    ...syne,
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.35)",
    marginBottom: "0.6rem",
    display: "block",
  };

  const inputStyle: React.CSSProperties = {
    width: "100%",
    background: "#0F2138",
    border: "1px solid rgba(255,255,255,0.18)",
    color: "rgba(255,255,255,0.9)",
    ...syne,
    fontSize: "14px",
    padding: "12px 14px",
    outline: "none",
    borderRadius: "6px",
  };

  const checkboxRowStyle: React.CSSProperties = {
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    padding: "10px 0",
    cursor: "pointer",
  };

  return (
    <div>
      <div style={{
        background: "#0F2138",
        border: "1px solid rgba(255,255,255,0.15)",
        padding: "2rem",
        boxShadow: "0 0 0 1px rgba(255,255,255,0.04), inset 0 1px 0 rgba(255,255,255,0.04)"
      }}>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>System or process name</label>
          <input
            type="text"
            value={systemName}
            onChange={(e) => setSystemName(e.target.value)}
            placeholder="e.g. Customer support triage AI"
            style={inputStyle}
          />
        </div>

        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>What does it do, and why?</label>
          <textarea
            value={purpose}
            onChange={(e) => setPurpose(e.target.value)}
            placeholder="e.g. Reads incoming support tickets and assigns a priority score to route them to the right team"
            rows={3}
            style={{ ...inputStyle, resize: "vertical", fontFamily: "'Syne', system-ui, sans-serif" }}
          />
        </div>

        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>What data does it process? Select all that apply</label>
          {DATA_TYPES.map((d) => (
            <label key={d.value} style={checkboxRowStyle}>
              <input
                type="checkbox"
                checked={dataTypes.has(d.value)}
                onChange={() => toggleSet(dataTypes, d.value, setDataTypes)}
                style={{ marginTop: "3px" }}
              />
              <span style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.75)", lineHeight: 1.5 }}>{d.label}</span>
            </label>
          ))}
        </div>

        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Does the system do any of the following?</label>
          <label style={checkboxRowStyle}>
            <input type="checkbox" checked={automatedDecision} onChange={() => setAutomatedDecision(!automatedDecision)} style={{ marginTop: "3px" }} />
            <span style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.75)", lineHeight: 1.5 }}>Make an automated decision with a legal or similarly significant effect (e.g. pricing, eligibility, hiring, credit) without meaningful human input</span>
          </label>
          <label style={checkboxRowStyle}>
            <input type="checkbox" checked={systematicMonitoring} onChange={() => setSystematicMonitoring(!systematicMonitoring)} style={{ marginTop: "3px" }} />
            <span style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.75)", lineHeight: 1.5 }}>Systematically monitor individuals (e.g. tracking behavior, profiling, continuous surveillance)</span>
          </label>
          <label style={checkboxRowStyle}>
            <input type="checkbox" checked={largeScale} onChange={() => setLargeScale(!largeScale)} style={{ marginTop: "3px" }} />
            <span style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.75)", lineHeight: 1.5 }}>Process data at large scale (many individuals, or a wide geographic reach)</span>
          </label>
        </div>

        <div>
          <label style={labelStyle}>Safeguards already in place, select all that apply</label>
          {SAFEGUARDS.map((s) => (
            <label key={s.value} style={checkboxRowStyle}>
              <input
                type="checkbox"
                checked={safeguards.has(s.value)}
                onChange={() => toggleSet(safeguards, s.value, setSafeguards)}
                style={{ marginTop: "3px" }}
              />
              <span style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.75)", lineHeight: 1.5 }}>{s.label}</span>
            </label>
          ))}
        </div>
      </div>

      <ResultsGate tool="dpia-generator" title="Enter your email to see your DPIA screening document. Free, plus occasional updates, unsubscribe anytime.">
        <div style={{ marginTop: "1.5rem" }}>
          <div style={{
            background: dpiaRequired ? "rgba(239,68,68,0.1)" : "rgba(74,222,128,0.08)",
            border: `1px solid ${dpiaRequired ? "rgba(239,68,68,0.3)" : "rgba(74,222,128,0.25)"}`,
            padding: "1.25rem 1.5rem",
            marginBottom: "1px",
          }}>
            <p style={{ ...syne, fontSize: "9px", fontWeight: 700, letterSpacing: "0.15em", textTransform: "uppercase", color: dpiaRequired ? "#f87171" : "#4ade80", marginBottom: "0.4rem" }}>
              Screening outcome
            </p>
            <p style={{ ...syne, fontSize: "14px", color: "rgba(255,255,255,0.85)", lineHeight: 1.6 }}>
              {dpiaRequired
                ? "A full DPIA is required under UK GDPR Article 35(3) before this processing begins or continues."
                : "A full DPIA is not automatically required based on what's selected — completing one is still good practice."}
            </p>
          </div>

          <div style={{
            background: "#102943",
            border: "1px solid rgba(239,68,68,0.2)",
            borderLeft: "3px solid #E5484D",
            padding: "1.5rem 1.75rem",
          }}>
            <p style={labelStyle}>Your DPIA screening document</p>
            <pre style={{ ...mono, fontSize: "12.5px", color: "rgba(255,255,255,0.85)", lineHeight: 1.7, marginBottom: "1.25rem", whiteSpace: "pre-wrap", wordBreak: "break-word" }}>
              {output}
            </pre>
            <button
              onClick={handleCopy}
              style={{
                background: copied ? "rgba(74,222,128,0.12)" : "#E5484D",
                color: copied ? "#4ade80" : "white",
                border: copied ? "1px solid rgba(74,222,128,0.3)" : "none",
                ...syne,
                fontSize: "0.85rem",
                fontWeight: 700,
                padding: "10px 22px",
                borderRadius: "9999px",
                cursor: "pointer",
                letterSpacing: "0.02em",
                transition: "all 0.2s",
              }}
            >
              {copied ? "Copied ✓" : "Copy to clipboard"}
            </button>
          </div>
        </div>
      </ResultsGate>

      <div style={{
        background: "#102943",
        border: "1px solid rgba(239,68,68,0.25)",
        padding: "2.25rem 2rem",
        textAlign: "center",
        marginTop: "1.5rem",
      }}>
        <p style={{ ...syne, fontSize: "1.1rem", fontWeight: 800, color: "white", letterSpacing: "-0.02em", marginBottom: "0.5rem" }}>
          A DPIA covers the data. It doesn't cover the decision.
        </p>
        <p style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.4)", lineHeight: 1.7, marginBottom: "1.5rem", maxWidth: "460px", margin: "0.5rem auto 1.5rem" }}>
          Once this screening says who can process what, boundary authorization records prove who actually approved it, when, and whether that approval has gone stale.
        </p>
        <Link href="/boundary-authorization-records" style={{
          display: "inline-block",
          background: "#E5484D",
          color: "white",
          ...syne,
          fontSize: "0.9rem",
          fontWeight: 700,
          padding: "14px 32px",
          borderRadius: "9999px",
          boxShadow: "0 8px 32px rgba(229,72,77,0.18)",
          textDecoration: "none",
          letterSpacing: "0.02em",
        }}>
          See how boundary authorization works
        </Link>
      </div>

      <p style={{ ...syne, fontSize: "11px", color: "rgba(255,255,255,0.25)", lineHeight: 1.7, marginTop: "1.5rem", textAlign: "center" }}>
        This tool gives a screening document, not legal advice or a substitute for a full DPIA. It follows the structure of the ICO&apos;s own screening checklist. Use the ICO&apos;s{" "}
        <a href="https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/guide-to-accountability-and-governance/accountability-framework/data-protection-impact-assessments/" target="_blank" rel="noopener noreferrer" style={{ color: "#E5484D", textDecoration: "none" }}>
          full DPIA guidance
        </a>{" "}
        to complete the assessment if one is required.
      </p>
    </div>
  );
}
