"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import React from "react";
import { ResultsGate } from "./ResultsGate";

const syne = { fontFamily: "'Syne', system-ui, sans-serif" } as React.CSSProperties;
const mono = { fontFamily: "'DM Mono', 'Courier New', monospace" } as React.CSSProperties;

const STATUS_OPTIONS = [
  { value: "in_service", label: "On the market / in service" },
  { value: "no_longer_available", label: "No longer available" },
  { value: "recalled", label: "Recalled" },
];

export function EUDatabaseRegistrationAssistant() {
  const [isHighRisk, setIsHighRisk] = useState(true);

  const [providerDetails, setProviderDetails] = useState("");
  const [submitterDetails, setSubmitterDetails] = useState("");
  const [authorizedRep, setAuthorizedRep] = useState("");
  const [tradeName, setTradeName] = useState("");
  const [purpose, setPurpose] = useState("");
  const [dataAndLogic, setDataAndLogic] = useState("");
  const [status, setStatus] = useState(STATUS_OPTIONS[0].value);
  const [certificateInfo, setCertificateInfo] = useState("");
  const [memberStates, setMemberStates] = useState("");
  const [conformityRef, setConformityRef] = useState("");
  const [instructionsUrl, setInstructionsUrl] = useState("");
  const [additionalUrl, setAdditionalUrl] = useState("");
  const [nonHighRiskGrounds, setNonHighRiskGrounds] = useState("");

  const [copied, setCopied] = useState(false);

  const output = useMemo(() => {
    const name = tradeName.trim() || "[AI system trade name]";

    if (!isHighRisk) {
      return `EU AI DATABASE REGISTRATION — DRAFT (Annex VIII, Section B: non-high-risk determination)
Generated by Red Flag AI Pro, ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}

This is a preparation draft, not a submission. Registration itself happens on the European Commission's own EU database portal — this tool has no connection to it and cannot submit on your behalf.

1. PROVIDER DETAILS
${providerDetails.trim() || "[Name, address, contact details]"}

2. AI SYSTEM TRADE NAME
${name}

3. APPLICABLE CONDITION UNDER ARTICLE 6(3)
[State which of the Article 6(3) conditions applies — narrow procedural task, improving a completed human activity's result, detecting decision-making patterns without replacing human assessment, or a preparatory task]

4. GROUNDS FOR NON-HIGH-RISK DETERMINATION
${nonHighRiskGrounds.trim() || "[Short summary of why the system is considered not high-risk despite falling within an Annex III use case]"}

This draft covers the Section B fields at a summary level. The Commission's actual submission template (set under Article 71(5)) may itemize this differently — check the live portal before submitting.`;
    }

    return `EU AI DATABASE REGISTRATION — DRAFT (Annex VIII, Section A: high-risk AI system)
Generated by Red Flag AI Pro, ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}

This is a preparation draft, not a submission. Registration itself happens on the European Commission's own EU database portal — this tool has no connection to it and cannot submit on your behalf.

1. PROVIDER'S NAME, ADDRESS AND CONTACT DETAILS
${providerDetails.trim() || "[Provider name, address, contact details]"}

2. SUBMITTER'S DETAILS (if different from provider)
${submitterDetails.trim() || "[Name, address, contact details, or leave blank if same as provider]"}

3. AUTHORIZED REPRESENTATIVE (if applicable)
${authorizedRep.trim() || "[Name, address, contact details, or leave blank if not applicable]"}

4. AI SYSTEM TRADE NAME AND IDENTIFICATION REFERENCE
${name}

5. INTENDED PURPOSE, COMPONENTS AND SUPPORTED FUNCTIONS
${purpose.trim() || "[Describe what the system is for, its components, and what functions it supports]"}

6. DATA AND OPERATING LOGIC
${dataAndLogic.trim() || "[A basic, concise description of the information used by the system — data, inputs — and its operating logic]"}

7. SYSTEM STATUS
${STATUS_OPTIONS.find((s) => s.value === status)?.label}

8. CERTIFICATE DETAILS (if a notified body was involved)
${certificateInfo.trim() || "[Certificate type, number, expiry date, and notified body identification number, or leave blank if self-assessed]"}

9. SCANNED CERTIFICATE COPY
[Attach when submitting on the actual portal — not entered here]

10. MEMBER STATES WHERE PLACED ON MARKET OR PUT INTO SERVICE
${memberStates.trim() || "[List the Member States, or note if EU-wide]"}

11. EU DECLARATION OF CONFORMITY
${conformityRef.trim() || "[Reference or attach a copy when submitting]"}

12. ELECTRONIC INSTRUCTIONS FOR USE
${instructionsUrl.trim() || "[Link or reference — not required for law enforcement, migration, asylum, or border control systems]"}

13. URL FOR ADDITIONAL INFORMATION (optional)
${additionalUrl.trim() || "[Optional]"}

This draft covers the 13 Section A fields listed in Annex VIII. The Commission's actual submission template (set under Article 71(5)) may itemize or format this differently — check the live portal before submitting, and confirm which fields apply to your specific system.`;
  }, [isHighRisk, providerDetails, submitterDetails, authorizedRep, tradeName, purpose, dataAndLogic, status, certificateInfo, memberStates, conformityRef, instructionsUrl, additionalUrl, nonHighRiskGrounds]);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard not available — text is selectable regardless
    }
  }

  const labelStyle: React.CSSProperties = {
    ...syne,
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.35)",
    marginBottom: "0.6rem",
    display: "block",
  };

  const inputStyle: React.CSSProperties = {
    width: "100%",
    background: "#0F2138",
    border: "1px solid rgba(255,255,255,0.18)",
    color: "rgba(255,255,255,0.9)",
    ...syne,
    fontSize: "14px",
    padding: "12px 14px",
    outline: "none",
    borderRadius: "6px",
  };

  const textareaStyle: React.CSSProperties = { ...inputStyle, resize: "vertical", fontFamily: "'Syne', system-ui, sans-serif" };

  return (
    <div>
      <div style={{
        background: "rgba(201,166,107,0.08)",
        border: "1px solid rgba(201,166,107,0.3)",
        borderLeft: "3px solid #C9A66B",
        padding: "1.25rem 1.5rem",
        marginBottom: "1.5rem",
      }}>
        <p style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.8)", lineHeight: 1.6 }}>
          This prepares the information the EU database asks for under Annex VIII. It does not submit anything — registration happens on the European Commission&apos;s own portal, which requires the provider&apos;s own account there.
        </p>
      </div>

      <div style={{ background: "#0F2138", border: "1px solid rgba(255,255,255,0.15)", padding: "2rem", marginBottom: "1.5rem" }}>
        <label style={labelStyle}>Is this system high-risk (Annex III), or are you self-determining it's not high-risk under Article 6(3)?</label>
        <div style={{ display: "flex", gap: "10px" }}>
          <button
            onClick={() => setIsHighRisk(true)}
            style={{
              flex: 1, padding: "12px", borderRadius: "6px", cursor: "pointer",
              background: isHighRisk ? "#E5484D" : "#0A1628",
              color: isHighRisk ? "white" : "rgba(255,255,255,0.6)",
              border: isHighRisk ? "none" : "1px solid rgba(255,255,255,0.15)",
              ...syne, fontSize: "13px", fontWeight: 700,
            }}
          >
            High-risk (Section A)
          </button>
          <button
            onClick={() => setIsHighRisk(false)}
            style={{
              flex: 1, padding: "12px", borderRadius: "6px", cursor: "pointer",
              background: !isHighRisk ? "#E5484D" : "#0A1628",
              color: !isHighRisk ? "white" : "rgba(255,255,255,0.6)",
              border: !isHighRisk ? "none" : "1px solid rgba(255,255,255,0.15)",
              ...syne, fontSize: "13px", fontWeight: 700,
            }}
          >
            Self-determined not high-risk (Section B)
          </button>
        </div>
      </div>

      <div style={{
        background: "#0F2138",
        border: "1px solid rgba(255,255,255,0.15)",
        padding: "2rem",
        boxShadow: "0 0 0 1px rgba(255,255,255,0.04), inset 0 1px 0 rgba(255,255,255,0.04)"
      }}>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Provider's name, address and contact details</label>
          <textarea value={providerDetails} onChange={(e) => setProviderDetails(e.target.value)} rows={2} style={textareaStyle} />
        </div>

        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>AI system trade name</label>
          <input type="text" value={tradeName} onChange={(e) => setTradeName(e.target.value)} placeholder="e.g. RiskScore Pro v2" style={inputStyle} />
        </div>

        {isHighRisk ? (
          <>
            <div style={{ marginBottom: "1.5rem" }}>
              <label style={labelStyle}>Submitter's details (if different from provider)</label>
              <textarea value={submitterDetails} onChange={(e) => setSubmitterDetails(e.target.value)} rows={2} style={textareaStyle} />
            </div>
            <div style={{ marginBottom: "1.5rem" }}>
              <label style={labelStyle}>Authorized representative (if applicable)</label>
              <textarea value={authorizedRep} onChange={(e) => setAuthorizedRep(e.target.value)} rows={2} style={textareaStyle} />
            </div>
            <div style={{ marginBottom: "1.5rem" }}>
              <label style={labelStyle}>Intended purpose, components and supported functions</label>
              <textarea value={purpose} onChange={(e) => setPurpose(e.target.value)} rows={3} style={textareaStyle} />
            </div>
            <div style={{ marginBottom: "1.5rem" }}>
              <label style={labelStyle}>Data used and operating logic</label>
              <textarea value={dataAndLogic} onChange={(e) => setDataAndLogic(e.target.value)} rows={3} style={textareaStyle} />
            </div>
            <div style={{ marginBottom: "1.5rem" }}>
              <label style={labelStyle}>System status</label>
              <select value={status} onChange={(e) => setStatus(e.target.value)} style={{ ...inputStyle, appearance: "none" }}>
                {STATUS_OPTIONS.map((s) => (
                  <option key={s.value} value={s.value} style={{ background: "#0F2138" }}>{s.label}</option>
                ))}
              </select>
            </div>
            <div style={{ marginBottom: "1.5rem" }}>
              <label style={labelStyle}>Certificate details (if a notified body was involved)</label>
              <textarea value={certificateInfo} onChange={(e) => setCertificateInfo(e.target.value)} rows={2} style={textareaStyle} placeholder="Certificate type, number, expiry, notified body ID" />
            </div>
            <div style={{ marginBottom: "1.5rem" }}>
              <label style={labelStyle}>Member States where placed on market or put into service</label>
              <input type="text" value={memberStates} onChange={(e) => setMemberStates(e.target.value)} placeholder="e.g. Ireland, Germany, or 'all EU Member States'" style={inputStyle} />
            </div>
            <div style={{ marginBottom: "1.5rem" }}>
              <label style={labelStyle}>EU declaration of conformity (reference)</label>
              <input type="text" value={conformityRef} onChange={(e) => setConformityRef(e.target.value)} style={inputStyle} />
            </div>
            <div style={{ marginBottom: "1.5rem" }}>
              <label style={labelStyle}>Electronic instructions for use (link)</label>
              <input type="text" value={instructionsUrl} onChange={(e) => setInstructionsUrl(e.target.value)} style={inputStyle} />
            </div>
            <div>
              <label style={labelStyle}>URL for additional information (optional)</label>
              <input type="text" value={additionalUrl} onChange={(e) => setAdditionalUrl(e.target.value)} style={inputStyle} />
            </div>
          </>
        ) : (
          <div>
            <label style={labelStyle}>Grounds for the non-high-risk determination</label>
            <textarea value={nonHighRiskGrounds} onChange={(e) => setNonHighRiskGrounds(e.target.value)} rows={4} placeholder="Which Article 6(3) condition applies, and why — a narrow procedural task, improving the result of a completed human activity, detecting decision-making patterns without replacing human assessment, or a preparatory task" style={textareaStyle} />
          </div>
        )}
      </div>

      <ResultsGate tool="eu-database-registration-assistant" title="Enter your email to see your registration draft. Free, plus occasional updates, unsubscribe anytime.">
        <div style={{ marginTop: "1.5rem" }}>
          <div style={{
            background: "#102943",
            border: "1px solid rgba(239,68,68,0.2)",
            borderLeft: "3px solid #E5484D",
            padding: "1.5rem 1.75rem",
          }}>
            <p style={labelStyle}>Your registration draft</p>
            <pre style={{ ...mono, fontSize: "12.5px", color: "rgba(255,255,255,0.85)", lineHeight: 1.7, marginBottom: "1.25rem", whiteSpace: "pre-wrap", wordBreak: "break-word" }}>
              {output}
            </pre>
            <button
              onClick={handleCopy}
              style={{
                background: copied ? "rgba(74,222,128,0.12)" : "#E5484D",
                color: copied ? "#4ade80" : "white",
                border: copied ? "1px solid rgba(74,222,128,0.3)" : "none",
                ...syne,
                fontSize: "0.85rem",
                fontWeight: 700,
                padding: "10px 22px",
                borderRadius: "9999px",
                cursor: "pointer",
                letterSpacing: "0.02em",
                transition: "all 0.2s",
              }}
            >
              {copied ? "Copied ✓" : "Copy to clipboard"}
            </button>
          </div>
        </div>
      </ResultsGate>

      <div style={{
        background: "#102943",
        border: "1px solid rgba(239,68,68,0.25)",
        padding: "2.25rem 2rem",
        textAlign: "center",
        marginTop: "1.5rem",
      }}>
        <p style={{ ...syne, fontSize: "1.1rem", fontWeight: 800, color: "white", letterSpacing: "-0.02em", marginBottom: "0.5rem" }}>
          This drafts the entry. It doesn&apos;t prove who approved putting it there.
        </p>
        <p style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.4)", lineHeight: 1.7, marginBottom: "1.5rem", maxWidth: "460px", margin: "0.5rem auto 1.5rem" }}>
          Boundary authorization records seal who approved this system, in what role, before it ever reached the database.
        </p>
        <Link href="/boundary-authorization-records" style={{
          display: "inline-block",
          background: "#E5484D",
          color: "white",
          ...syne,
          fontSize: "0.9rem",
          fontWeight: 700,
          padding: "14px 32px",
          borderRadius: "9999px",
          boxShadow: "0 8px 32px rgba(229,72,77,0.18)",
          textDecoration: "none",
          letterSpacing: "0.02em",
        }}>
          See how boundary authorization works
        </Link>
      </div>

      <p style={{ ...syne, fontSize: "11px", color: "rgba(255,255,255,0.25)", lineHeight: 1.7, marginTop: "1.5rem", textAlign: "center" }}>
        This tool produces a preparation draft, not a submission, legal advice, or certification. It follows Annex VIII of the EU AI Act as published. The Commission's actual submission format is set separately under Article 71(5) and may differ — confirm on the live portal before you register.
      </p>
    </div>
  );
}
