"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import React from "react";
import { ResultsGate } from "./ResultsGate";

const syne = { fontFamily: "'Syne', system-ui, sans-serif" } as React.CSSProperties;
const mono = { fontFamily: "'DM Mono', 'Courier New', monospace" } as React.CSSProperties;

export function FRIAAssistant() {
  const [systemName, setSystemName] = useState("");
  const [processes, setProcesses] = useState("");
  const [usagePeriod, setUsagePeriod] = useState("");
  const [affectedParties, setAffectedParties] = useState("");
  const [specificRisks, setSpecificRisks] = useState("");
  const [oversightMeasures, setOversightMeasures] = useState("");
  const [mitigationMeasures, setMitigationMeasures] = useState("");
  const [copied, setCopied] = useState(false);

  const output = useMemo(() => {
    const name = systemName.trim() || "[AI system name]";
    return `FUNDAMENTAL RIGHTS IMPACT ASSESSMENT — DRAFT (Article 27)
Generated by Red Flag AI Pro, ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}

This is a preparation draft, not a submitted assessment. If your organization is required to file this (see the note below), results go to the market surveillance authority on the AI Office's own template.

SYSTEM: ${name}

1. DEPLOYER PROCESSES
${processes.trim() || "[Describe the processes in which this high-risk AI system will actually be used]"}

2. PERIOD AND FREQUENCY OF USE
${usagePeriod.trim() || "[How long, and how often, is this system intended to be used?]"}

3. AFFECTED PERSONS AND GROUPS
${affectedParties.trim() || "[Which categories of natural persons or groups are likely to be affected by its use?]"}

4. SPECIFIC RISKS OF HARM
${specificRisks.trim() || "[For each affected category above, what specific risks of harm to their fundamental rights does this pose?]"}

5. HUMAN OVERSIGHT MEASURES
${oversightMeasures.trim() || "[How will human oversight be implemented, per the system's instructions for use?]"}
See boundary authorization records for a way to make this provable, not just described: redflagaipro.com/boundary-authorization-records

6. RISK MITIGATION MEASURES
${mitigationMeasures.trim() || "[What measures will be taken if these risks materialize? Include internal governance arrangements and complaint mechanisms.]"}

WHO NEEDS TO FILE THIS
Article 27 applies to: public bodies governed by public law, private entities providing public services, and deployers of high-risk systems in specific Annex III categories (biometric verification/emotion recognition context, and credit scoring/insurance risk assessment). It must be done before first deployment and updated if any element changes.

This draft covers the 6 elements listed in Article 27(1). The Commission's actual submission template may itemize this differently — confirm on the live AI Office portal, and confirm with counsel whether your organization is in scope at all.`;
  }, [systemName, processes, usagePeriod, affectedParties, specificRisks, oversightMeasures, mitigationMeasures]);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard not available — text is selectable regardless
    }
  }

  const labelStyle: React.CSSProperties = {
    ...syne, fontSize: "10px", fontWeight: 700, letterSpacing: "0.18em", textTransform: "uppercase",
    color: "rgba(255,255,255,0.35)", marginBottom: "0.6rem", display: "block",
  };
  const inputStyle: React.CSSProperties = {
    width: "100%", background: "#0F2138", border: "1px solid rgba(255,255,255,0.18)", color: "rgba(255,255,255,0.9)",
    ...syne, fontSize: "14px", padding: "12px 14px", outline: "none", borderRadius: "6px",
  };
  const textareaStyle: React.CSSProperties = { ...inputStyle, resize: "vertical", fontFamily: "'Syne', system-ui, sans-serif" };

  return (
    <div>
      <div style={{
        background: "rgba(201,166,107,0.08)", border: "1px solid rgba(201,166,107,0.3)", borderLeft: "3px solid #C9A66B",
        padding: "1.25rem 1.5rem", marginBottom: "1.5rem",
      }}>
        <p style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.8)", lineHeight: 1.6 }}>
          This is separate from a DPIA. A DPIA covers data protection; a Fundamental Rights Impact Assessment covers broader rights impacts, and only applies to certain deployers (public bodies, banks, insurers, and specific Annex III use cases). Check whether it applies to you before assuming it does.
        </p>
      </div>

      <div style={{ background: "#0F2138", border: "1px solid rgba(255,255,255,0.15)", padding: "2rem" }}>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>AI system name</label>
          <input type="text" value={systemName} onChange={(e) => setSystemName(e.target.value)} style={inputStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Deployer processes — how is it used in practice?</label>
          <textarea value={processes} onChange={(e) => setProcesses(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Period and frequency of use</label>
          <textarea value={usagePeriod} onChange={(e) => setUsagePeriod(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Affected persons and groups</label>
          <textarea value={affectedParties} onChange={(e) => setAffectedParties(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Specific risks of harm to their rights</label>
          <textarea value={specificRisks} onChange={(e) => setSpecificRisks(e.target.value)} rows={3} style={textareaStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Human oversight measures</label>
          <textarea value={oversightMeasures} onChange={(e) => setOversightMeasures(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div>
          <label style={labelStyle}>Mitigation measures if risks materialize</label>
          <textarea value={mitigationMeasures} onChange={(e) => setMitigationMeasures(e.target.value)} rows={2} style={textareaStyle} />
        </div>
      </div>

      <ResultsGate tool="fria-assistant" title="Enter your email to see your FRIA draft. Free, plus occasional updates, unsubscribe anytime.">
        <div style={{ marginTop: "1.5rem" }}>
          <div style={{ background: "#102943", border: "1px solid rgba(239,68,68,0.2)", borderLeft: "3px solid #E5484D", padding: "1.5rem 1.75rem" }}>
            <p style={labelStyle}>Your FRIA draft</p>
            <pre style={{ ...mono, fontSize: "12.5px", color: "rgba(255,255,255,0.85)", lineHeight: 1.7, marginBottom: "1.25rem", whiteSpace: "pre-wrap", wordBreak: "break-word" }}>
              {output}
            </pre>
            <button
              onClick={handleCopy}
              style={{
                background: copied ? "rgba(74,222,128,0.12)" : "#E5484D", color: copied ? "#4ade80" : "white",
                border: copied ? "1px solid rgba(74,222,128,0.3)" : "none", ...syne, fontSize: "0.85rem", fontWeight: 700,
                padding: "10px 22px", borderRadius: "9999px", cursor: "pointer", letterSpacing: "0.02em", transition: "all 0.2s",
              }}
            >
              {copied ? "Copied ✓" : "Copy to clipboard"}
            </button>
          </div>
        </div>
      </ResultsGate>

      <div style={{ background: "#102943", border: "1px solid rgba(239,68,68,0.25)", padding: "2.25rem 2rem", textAlign: "center", marginTop: "1.5rem" }}>
        <p style={{ ...syne, fontSize: "1.1rem", fontWeight: 800, color: "white", letterSpacing: "-0.02em", marginBottom: "0.5rem" }}>
          This documents the oversight you designed. It doesn&apos;t prove it happened.
        </p>
        <p style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.4)", lineHeight: 1.7, marginBottom: "1.5rem", maxWidth: "460px", margin: "0.5rem auto 1.5rem" }}>
          Boundary authorization records seal who approved this system, in what role, so section 5 above becomes provable rather than asserted.
        </p>
        <Link href="/boundary-authorization-records" style={{
          display: "inline-block", background: "#E5484D", color: "white", ...syne, fontSize: "0.9rem", fontWeight: 700,
          padding: "14px 32px", borderRadius: "9999px", boxShadow: "0 8px 32px rgba(229,72,77,0.18)", textDecoration: "none", letterSpacing: "0.02em",
        }}>
          See how boundary authorization works
        </Link>
      </div>

      <p style={{ ...syne, fontSize: "11px", color: "rgba(255,255,255,0.25)", lineHeight: 1.7, marginTop: "1.5rem", textAlign: "center" }}>
        This tool produces a preparation draft, not a submission, legal advice, or certification. It follows Article 27 of the EU AI Act as published. Confirm whether the obligation applies to your organization, and the current submission format, with legal counsel.
      </p>
    </div>
  );
}
