"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import React from "react";
import { ResultsGate } from "./ResultsGate";

const syne = { fontFamily: "'Syne', system-ui, sans-serif" } as React.CSSProperties;
const mono = { fontFamily: "'DM Mono', 'Courier New', monospace" } as React.CSSProperties;

export function MonitoringPlanGenerator() {
  const [systemName, setSystemName] = useState("");
  const [metrics, setMetrics] = useState("");
  const [dataSources, setDataSources] = useState("");
  const [reviewCadence, setReviewCadence] = useState("");
  const [thresholds, setThresholds] = useState("");
  const [corrective, setCorrective] = useState("");
  const [recordKeeping, setRecordKeeping] = useState("");
  const [copied, setCopied] = useState(false);

  const output = useMemo(() => {
    const name = systemName.trim() || "[AI system name]";
    return `POST-MARKET MONITORING PLAN — DRAFT (Article 72)
Generated by Red Flag AI Pro, ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}

This is a plan, not the monitoring itself. It documents how you intend to watch this system's performance over time. Actually collecting and analyzing the data described below requires your own infrastructure — this tool doesn't ingest or monitor anything live.

SYSTEM: ${name}

1. PERFORMANCE METRICS AND BASELINES
${metrics.trim() || "[What metrics will you track — accuracy, error rate, complaint volume, override rate — and what's the baseline value for each?]"}

2. DATA SOURCES AND COLLECTION METHOD
${dataSources.trim() || "[Where does this data come from, and how is it collected — logs, user reports, sampled review?]"}

3. REVIEW CADENCE
${reviewCadence.trim() || "[How often is this data analyzed, and by whom?]"}

4. ESCALATION THRESHOLDS
${thresholds.trim() || "[What values or changes trigger escalation — a metric crossing a line, a spike in complaints?]"}

5. CORRECTIVE ACTION PROCEDURE
${corrective.trim() || "[What happens when a threshold is crossed — who is notified, what's the response process?]"}

6. RECORD-KEEPING FORMAT
${recordKeeping.trim() || "[How is monitoring data and each review kept, in a form a regulator could later verify?]"}

This plan becomes part of your Annex IV technical documentation. The Commission's own implementing act sets the formal template and full list of required elements (due by 2 February 2026) — confirm the current official template before finalizing, as this draft may not match its exact structure.`;
  }, [systemName, metrics, dataSources, reviewCadence, thresholds, corrective, recordKeeping]);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard not available — text is selectable regardless
    }
  }

  const labelStyle: React.CSSProperties = {
    ...syne, fontSize: "10px", fontWeight: 700, letterSpacing: "0.18em", textTransform: "uppercase",
    color: "rgba(255,255,255,0.35)", marginBottom: "0.6rem", display: "block",
  };
  const inputStyle: React.CSSProperties = {
    width: "100%", background: "#0F2138", border: "1px solid rgba(255,255,255,0.18)", color: "rgba(255,255,255,0.9)",
    ...syne, fontSize: "14px", padding: "12px 14px", outline: "none", borderRadius: "6px",
  };
  const textareaStyle: React.CSSProperties = { ...inputStyle, resize: "vertical", fontFamily: "'Syne', system-ui, sans-serif" };

  return (
    <div>
      <div style={{
        background: "rgba(201,166,107,0.08)", border: "1px solid rgba(201,166,107,0.3)", borderLeft: "3px solid #C9A66B",
        padding: "1.25rem 1.5rem", marginBottom: "1.5rem",
      }}>
        <p style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.8)", lineHeight: 1.6 }}>
          This drafts the <strong>plan</strong>, not the monitoring. Actually watching a live system for drift or bias needs your own infrastructure connected to your model — this tool has no connection to your AI system.
        </p>
      </div>

      <div style={{ background: "#0F2138", border: "1px solid rgba(255,255,255,0.15)", padding: "2rem" }}>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>AI system name</label>
          <input type="text" value={systemName} onChange={(e) => setSystemName(e.target.value)} style={inputStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Performance metrics and baselines</label>
          <textarea value={metrics} onChange={(e) => setMetrics(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Data sources and collection method</label>
          <textarea value={dataSources} onChange={(e) => setDataSources(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Review cadence — how often, by whom?</label>
          <textarea value={reviewCadence} onChange={(e) => setReviewCadence(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Escalation thresholds</label>
          <textarea value={thresholds} onChange={(e) => setThresholds(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Corrective action procedure</label>
          <textarea value={corrective} onChange={(e) => setCorrective(e.target.value)} rows={2} style={textareaStyle} />
        </div>
        <div>
          <label style={labelStyle}>Record-keeping format</label>
          <textarea value={recordKeeping} onChange={(e) => setRecordKeeping(e.target.value)} rows={2} style={textareaStyle} />
        </div>
      </div>

      <ResultsGate tool="monitoring-plan-generator" title="Enter your email to see your monitoring plan draft. Free, plus occasional updates, unsubscribe anytime.">
        <div style={{ marginTop: "1.5rem" }}>
          <div style={{ background: "#102943", border: "1px solid rgba(239,68,68,0.2)", borderLeft: "3px solid #E5484D", padding: "1.5rem 1.75rem" }}>
            <p style={labelStyle}>Your monitoring plan draft</p>
            <pre style={{ ...mono, fontSize: "12.5px", color: "rgba(255,255,255,0.85)", lineHeight: 1.7, marginBottom: "1.25rem", whiteSpace: "pre-wrap", wordBreak: "break-word" }}>
              {output}
            </pre>
            <button
              onClick={handleCopy}
              style={{
                background: copied ? "rgba(74,222,128,0.12)" : "#E5484D", color: copied ? "#4ade80" : "white",
                border: copied ? "1px solid rgba(74,222,128,0.3)" : "none", ...syne, fontSize: "0.85rem", fontWeight: 700,
                padding: "10px 22px", borderRadius: "9999px", cursor: "pointer", letterSpacing: "0.02em", transition: "all 0.2s",
              }}
            >
              {copied ? "Copied ✓" : "Copy to clipboard"}
            </button>
          </div>
        </div>
      </ResultsGate>

      <div style={{ background: "#102943", border: "1px solid rgba(239,68,68,0.25)", padding: "2.25rem 2rem", textAlign: "center", marginTop: "1.5rem" }}>
        <p style={{ ...syne, fontSize: "1.1rem", fontWeight: 800, color: "white", letterSpacing: "-0.02em", marginBottom: "0.5rem" }}>
          A plan says what you&apos;ll watch. A sealed record proves you actually looked.
        </p>
        <p style={{ ...syne, fontSize: "13px", color: "rgba(255,255,255,0.4)", lineHeight: 1.7, marginBottom: "1.5rem", maxWidth: "460px", margin: "0.5rem auto 1.5rem" }}>
          Sentinel seals every governance review as it happens, with a timestamp nobody here controls, so the review cadence above becomes a provable history rather than a policy nobody checks.
        </p>
        <Link href="/sentinel" style={{
          display: "inline-block", background: "#E5484D", color: "white", ...syne, fontSize: "0.9rem", fontWeight: 700,
          padding: "14px 32px", borderRadius: "9999px", boxShadow: "0 8px 32px rgba(229,72,77,0.18)", textDecoration: "none", letterSpacing: "0.02em",
        }}>
          See how Sentinel seals reviews
        </Link>
      </div>

      <p style={{ ...syne, fontSize: "11px", color: "rgba(255,255,255,0.25)", lineHeight: 1.7, marginTop: "1.5rem", textAlign: "center" }}>
        This tool produces a plan draft, not a certification or the monitoring itself. It follows Article 72 of the EU AI Act as published. The Commission's formal template may differ — confirm before finalizing.
      </p>
    </div>
  );
}
